[versions]
room = "2.4.0-alpha04"
compose = "1.1.0-alpha04"
composeHilt = "2.4.0-beta01"
composeHiltNavigation = "1.0.0-alpha03"
compseNavigation = "2.4.0-alpha09"
hilt = "2.38.1"
appCompat = "1.3.1"
coreKtx = "1.6.0"
protobuf = "3.12.0"
dataStore = "1.0.0"
coroutine = "1.5.2"
lifecyleRuntime = "2.4.0"

#[plugins]
#spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
#gradleDependencyUpdate = { id = "com.github.ben-manes.versions", version.ref = "gradleDependencyUpdate" }

[libraries]
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
ktx-core = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecyleRuntime" }

compose-core = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compse-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose" }

compose-hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "composeHiltNavigation" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "compseNavigation" }

compose-lifecycle = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "composeHilt" }
compose-icon-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }

datastore-androidx = { module = "androidx.datastore:datastore", version.ref = "dataStore" }
datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "dataStore" }

protobuf = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf" }

hilt-core = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

room-common = { module = "androidx.room:room-common", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

coroutine = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutine" }


[bundles]
room = ["room-common", "room-compiler", "room-ktx", "room-runtime"]